# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PMOD_BLE.xdc

# Block Designs: bd/Ground_Station/Ground_Station.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ground_Station || ORIG_REF_NAME==Ground_Station} -quiet] -quiet

# IP: bd/Ground_Station/ip/Ground_Station_zynq_ultra_ps_e_0_0/Ground_Station_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ground_Station_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Ground_Station_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: c:/Users/ist21005/Documents/GS_Vivado/GroundStation_BLE/GroundStation_BLE.gen/sources_1/bd/Ground_Station/Ground_Station_ooc.xdc
