# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PMOD_ESP32.xdc

# XDC: new/PMOD_BLE.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADD_2_0_0/design_1_ADD_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADD_2_0_0 || ORIG_REF_NAME==design_1_ADD_2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_6/design_1_axi_smc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_6 || ORIG_REF_NAME==design_1_axi_smc_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_AES_GCM_0_10/design_1_AXI_AES_GCM_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI_AES_GCM_0_10 || ORIG_REF_NAME==design_1_AXI_AES_GCM_0_10} -quiet] -quiet

# XDC: c:/Users/ist21005/Documents/GS_Vivado/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
