# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PmodBT2.xdc

# Block Designs: bd/ZCU102/ZCU102.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZCU102 || ORIG_REF_NAME==ZCU102} -quiet] -quiet

# IP: bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZCU102_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ZCU102_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.gen/sources_1/bd/ZCU102/ZCU102_ooc.xdc
