# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.srcs/sources_1/bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ZCU102_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.gen/sources_1/bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZCU102_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.gen/sources_1/bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZCU102_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.srcs/sources_1/bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ZCU102_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.gen/sources_1/bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZCU102_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ist21005/Documents/Board_Practice/pmod_ip/pmod_ip.gen/sources_1/bd/ZCU102/ip/ZCU102_zynq_ultra_ps_e_0_0/ZCU102_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZCU102_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
